---
- name: Modify /etc/hosts file
  hosts: kube
  become: yes
  tasks:
    - name: Add entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        insertafter: "^127.0.0.1"
      loop:
        - "52.79.137.65 master"
        - "52.79.253.215 worker01"
        - "52.78.159.56 worker02"
        - "3.35.230.208 worker03"
